#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elcondor.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class TblHotelViewDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTblHotelView(TblHotelView instance);
    partial void UpdateTblHotelView(TblHotelView instance);
    partial void DeleteTblHotelView(TblHotelView instance);
    #endregion
		
		public TblHotelViewDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TblHotelViewDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TblHotelViewDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TblHotelViewDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TblHotelView> TblHotelViews
		{
			get
			{
				return this.GetTable<TblHotelView>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="elcondoruser.TblHotel")]
	public partial class TblHotelView : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _CountryId;
		
		private string _CityId;
		
		private string _DistrictId;
		
		private System.Nullable<int> _DistanceToBeach;
		
		private string _AccomodationTypeId;
		
		private System.Nullable<int> _StarRating;
		
		private string _Description;
		
		private System.Nullable<bool> _IsTop10;
		
		private System.Nullable<double> _MinPricePerPerson;
		
		private System.Nullable<int> _MaxPeople;
		
		private System.Nullable<int> _HotelStatusId;
		
		private string _HotelStatusName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCountryNameChanging(string value);
    partial void OnCountryNameChanged();
    partial void OnCityNameChanging(string value);
    partial void OnCityNameChanged();
    partial void OnDistrictNameChanging(string value);
    partial void OnDistrictNameChanged();
    partial void OnDistanceToBeachChanging(System.Nullable<int> value);
    partial void OnDistanceToBeachChanged();
    partial void OnAccomodationTypeNameChanging(string value);
    partial void OnAccomodationTypeNameChanged();
    partial void OnStarRatingChanging(System.Nullable<int> value);
    partial void OnStarRatingChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnIsTop10Changing(System.Nullable<bool> value);
    partial void OnIsTop10Changed();
    partial void OnMinPricePerPersonChanging(System.Nullable<double> value);
    partial void OnMinPricePerPersonChanged();
    partial void OnMaxPeopleChanging(System.Nullable<int> value);
    partial void OnMaxPeopleChanged();
    partial void OnHotelStatusIdChanging(System.Nullable<int> value);
    partial void OnHotelStatusIdChanged();
    partial void OnHotelStatusNameChanging(string value);
    partial void OnHotelStatusNameChanged();
    #endregion
		
		public TblHotelView()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryId", DbType="NVarChar(200) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.WhenChanged)]
		public string CountryName
		{
			get
			{
				return this._CountryId;
			}
			set
			{
				if ((this._CountryId != value))
				{
					this.OnCountryNameChanging(value);
					this.SendPropertyChanging();
					this._CountryId = value;
					this.SendPropertyChanged("CountryName");
					this.OnCountryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityId", DbType="NVarChar(200) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.WhenChanged)]
		public string CityName
		{
			get
			{
				return this._CityId;
			}
			set
			{
				if ((this._CityId != value))
				{
					this.OnCityNameChanging(value);
					this.SendPropertyChanging();
					this._CityId = value;
					this.SendPropertyChanged("CityName");
					this.OnCityNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictId", DbType="NVarChar(200) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.WhenChanged)]
		public string DistrictName
		{
			get
			{
				return this._DistrictId;
			}
			set
			{
				if ((this._DistrictId != value))
				{
					this.OnDistrictNameChanging(value);
					this.SendPropertyChanging();
					this._DistrictId = value;
					this.SendPropertyChanged("DistrictName");
					this.OnDistrictNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistanceToBeach", DbType="Int")]
		public System.Nullable<int> DistanceToBeach
		{
			get
			{
				return this._DistanceToBeach;
			}
			set
			{
				if ((this._DistanceToBeach != value))
				{
					this.OnDistanceToBeachChanging(value);
					this.SendPropertyChanging();
					this._DistanceToBeach = value;
					this.SendPropertyChanged("DistanceToBeach");
					this.OnDistanceToBeachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_AccomodationTypeId", DbType="NVarChar(200) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.WhenChanged)]
		public string AccomodationTypeName
		{
			get
			{
				return this._AccomodationTypeId;
			}
			set
			{
				if ((this._AccomodationTypeId != value))
				{
					this.OnAccomodationTypeNameChanging(value);
					this.SendPropertyChanging();
					this._AccomodationTypeId = value;
					this.SendPropertyChanged("AccomodationTypeName");
					this.OnAccomodationTypeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StarRating", DbType="Int")]
		public System.Nullable<int> StarRating
		{
			get
			{
				return this._StarRating;
			}
			set
			{
				if ((this._StarRating != value))
				{
					this.OnStarRatingChanging(value);
					this.SendPropertyChanging();
					this._StarRating = value;
					this.SendPropertyChanged("StarRating");
					this.OnStarRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(2000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsTop10", DbType="Bit")]
		public System.Nullable<bool> IsTop10
		{
			get
			{
				return this._IsTop10;
			}
			set
			{
				if ((this._IsTop10 != value))
				{
					this.OnIsTop10Changing(value);
					this.SendPropertyChanging();
					this._IsTop10 = value;
					this.SendPropertyChanged("IsTop10");
					this.OnIsTop10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinPricePerPerson", DbType="Float")]
		public System.Nullable<double> MinPricePerPerson
		{
			get
			{
				return this._MinPricePerPerson;
			}
			set
			{
				if ((this._MinPricePerPerson != value))
				{
					this.OnMinPricePerPersonChanging(value);
					this.SendPropertyChanging();
					this._MinPricePerPerson = value;
					this.SendPropertyChanged("MinPricePerPerson");
					this.OnMinPricePerPersonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxPeople", DbType="Int")]
		public System.Nullable<int> MaxPeople
		{
			get
			{
				return this._MaxPeople;
			}
			set
			{
				if ((this._MaxPeople != value))
				{
					this.OnMaxPeopleChanging(value);
					this.SendPropertyChanging();
					this._MaxPeople = value;
					this.SendPropertyChanged("MaxPeople");
					this.OnMaxPeopleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotelStatusId", DbType="Int")]
		public System.Nullable<int> HotelStatusId
		{
			get
			{
				return this._HotelStatusId;
			}
			set
			{
				if ((this._HotelStatusId != value))
				{
					this.OnHotelStatusIdChanging(value);
					this.SendPropertyChanging();
					this._HotelStatusId = value;
					this.SendPropertyChanged("HotelStatusId");
					this.OnHotelStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotelStatusName", DbType="NVarChar(200) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.WhenChanged)]
		public string HotelStatusName
		{
			get
			{
				return this._HotelStatusName;
			}
			set
			{
				if ((this._HotelStatusName != value))
				{
					this.OnHotelStatusNameChanging(value);
					this.SendPropertyChanging();
					this._HotelStatusName = value;
					this.SendPropertyChanged("HotelStatusName");
					this.OnHotelStatusNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
